---
version: 2

release:
  prerelease: auto
  name_template: "gtasks {{.Version}}"

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v3
    ldflags:
      - -X github.com/BRO3886/gtasks/cmd.Version={{.Version}}
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
