---
version: 2

release:
  prerelease: auto
  name_template: "gtasks {{.Version}}"

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags:
      - -X github.com/BRO3886/gtasks/cmd.Version={{.Version}}
archives:
  - replacements:
      linux: Linux
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
